/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package labextrap2_diegolara;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author diego
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    Deporte d;

    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_Principal = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        cb_q1 = new javax.swing.JCheckBox();
        cb_q2 = new javax.swing.JCheckBox();
        cb_q3 = new javax.swing.JCheckBox();
        cb_q4 = new javax.swing.JCheckBox();
        jb_add = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tf_nequipo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_puntos = new javax.swing.JTextField();
        jb_adde = new javax.swing.JButton();
        cb_tipoe = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tf_tnombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jb_addt = new javax.swing.JButton();
        cb_tipo = new javax.swing.JComboBox<>();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Periodos");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Q1");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Q2");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Q4");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Q5");
        treeNode1.add(treeNode2);
        jt_Principal.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jt_Principal);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(485, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Principal", jPanel1);

        jLabel1.setText("Nombre:");

        cb_q1.setText("Q1");

        cb_q2.setText("Q2");

        cb_q3.setText("Q3");

        cb_q4.setText("Q4");

        jb_add.setText("Agregar Deporte");
        jb_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_addMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_q4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cb_q2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                .addComponent(cb_q1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(cb_q3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jb_add, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(432, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(cb_q1)
                .addGap(18, 18, 18)
                .addComponent(cb_q2)
                .addGap(18, 18, 18)
                .addComponent(cb_q3)
                .addGap(18, 18, 18)
                .addComponent(cb_q4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_add)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar Deportes", jPanel2);

        jLabel3.setText("Nombre:");

        jLabel4.setText("Puntos:");

        jb_adde.setText("Agregar Equipo");
        jb_adde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_addeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_adde, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_tipoe, 0, 189, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_nequipo)
                                .addComponent(tf_puntos, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)))))
                .addContainerGap(412, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(cb_tipoe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_nequipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_puntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jb_adde)
                .addContainerGap(312, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar Equipos", jPanel3);

        jLabel5.setText("Nombre:");

        jLabel6.setText("Tipo:");

        jb_addt.setText("Agregar");
        jb_addt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_addtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_addt, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_tnombre)
                            .addComponent(cb_tipo, 0, 204, Short.MAX_VALUE))))
                .addContainerGap(462, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_tnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jb_addt)
                .addContainerGap(333, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar Torneos", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_addMouseClicked
        DefaultTreeModel m = (DefaultTreeModel) jt_Principal.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
        DefaultMutableTreeNode q1 = new DefaultMutableTreeNode("" + tf_nombre.getText());
        DefaultMutableTreeNode q2 = new DefaultMutableTreeNode("" + tf_nombre.getText());
        DefaultMutableTreeNode q4 = new DefaultMutableTreeNode("" + tf_nombre.getText());
        DefaultMutableTreeNode q5 = new DefaultMutableTreeNode("" + tf_nombre.getText());
        DefaultMutableTreeNode add1 = (DefaultMutableTreeNode) raiz.getChildAt(0);
        DefaultMutableTreeNode add2 = (DefaultMutableTreeNode) raiz.getChildAt(1);
        DefaultMutableTreeNode add3 = (DefaultMutableTreeNode) raiz.getChildAt(2);
        DefaultMutableTreeNode add4 = (DefaultMutableTreeNode) raiz.getChildAt(3);
        DefaultComboBoxModel model = (DefaultComboBoxModel) cb_tipo.getModel();
        DefaultComboBoxModel model2 = (DefaultComboBoxModel) cb_tipoe.getModel();
        model.addElement(tf_nombre.getText());
        d = new Deporte();
        if (cb_q1.isSelected()) {
            add1.add(q1);
        }
        if (cb_q2.isSelected()) {
            add2.add(q2);
        }
        if (cb_q3.isSelected()) {
            add3.add(q4);
        }
        if (cb_q4.isSelected()) {
            add4.add(q5);
        }
        m.reload();
        cb_tipo.setModel(model);
        cb_tipoe.setModel(model2);
        tf_nombre.setText("");
        JOptionPane.showMessageDialog(this, "Agregado");
    }//GEN-LAST:event_jb_addMouseClicked

    private void jb_addeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_addeMouseClicked
        Equipo e = new Equipo(tf_nequipo.getText(), Integer.parseInt(tf_puntos.getText()), cb_tipoe.getSelectedItem().toString());
        DefaultTreeModel m = (DefaultTreeModel) jt_Principal.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
        DefaultMutableTreeNode q1 = (DefaultMutableTreeNode) raiz.getChildAt(0);
        DefaultMutableTreeNode q2 = (DefaultMutableTreeNode) raiz.getChildAt(1);
        DefaultMutableTreeNode q3 = (DefaultMutableTreeNode) raiz.getChildAt(2);
        DefaultMutableTreeNode q4 = (DefaultMutableTreeNode) raiz.getChildAt(3);
        Torneo t = new Torneo(tf_tnombre.getText(), cb_tipo.getSelectedItem().toString());
        for (int i = 0; i < q1.getChildCount(); i++) {
            if (q1.getChildAt(i).toString().
                    equals(t.getTipo())) {
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(t);
                ((DefaultMutableTreeNode) q1.getChildAt(i)).add(p);
            }
        }
        for (int i = 0; i < q2.getChildCount(); i++) {
            if (q2.getChildAt(i).toString().
                    equals(t.getTipo())) {
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(t);
                ((DefaultMutableTreeNode) q2.getChildAt(i)).add(p);
            }
        }
        for (int i = 0; i < q3.getChildCount(); i++) {
            if (q3.getChildAt(i).toString().
                    equals(t.getTipo())) {
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(t);
                ((DefaultMutableTreeNode) q3.getChildAt(i)).add(p);
            }
        }
        for (int i = 0; i < q4.getChildCount(); i++) {
            if (q4.getChildAt(i).toString().
                    equals(t.getTipo())) {
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(t);
                ((DefaultMutableTreeNode) q4.getChildAt(i)).add(p);
            }
        }

        m.reload();

    }//GEN-LAST:event_jb_addeMouseClicked

    private void jb_addtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_addtMouseClicked
        DefaultTreeModel m = (DefaultTreeModel) jt_Principal.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
        DefaultMutableTreeNode q1 = (DefaultMutableTreeNode) raiz.getChildAt(0);
        DefaultMutableTreeNode q2 = (DefaultMutableTreeNode) raiz.getChildAt(1);
        DefaultMutableTreeNode q3 = (DefaultMutableTreeNode) raiz.getChildAt(2);
        DefaultMutableTreeNode q4 = (DefaultMutableTreeNode) raiz.getChildAt(3);
        Torneo t = new Torneo(tf_tnombre.getText(), cb_tipo.getSelectedItem().toString());
        for (int i = 0; i < q1.getChildCount(); i++) {
            if (q1.getChildAt(i).toString().
                    equals(t.getTipo())) {
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(t);
                ((DefaultMutableTreeNode) q1.getChildAt(i)).add(p);
            }
        }
        for (int i = 0; i < q2.getChildCount(); i++) {
            if (q2.getChildAt(i).toString().
                    equals(t.getTipo())) {
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(t);
                ((DefaultMutableTreeNode) q2.getChildAt(i)).add(p);
            }
        }
        for (int i = 0; i < q3.getChildCount(); i++) {
            if (q3.getChildAt(i).toString().
                    equals(t.getTipo())) {
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(t);
                ((DefaultMutableTreeNode) q3.getChildAt(i)).add(p);
            }
        }
        for (int i = 0; i < q4.getChildCount(); i++) {
            if (q4.getChildAt(i).toString().
                    equals(t.getTipo())) {
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(t);
                ((DefaultMutableTreeNode) q4.getChildAt(i)).add(p);
            }
        }

        m.reload();


    }//GEN-LAST:event_jb_addtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cb_q1;
    private javax.swing.JCheckBox cb_q2;
    private javax.swing.JCheckBox cb_q3;
    private javax.swing.JCheckBox cb_q4;
    private javax.swing.JComboBox<String> cb_tipo;
    private javax.swing.JComboBox<String> cb_tipoe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jb_add;
    private javax.swing.JButton jb_adde;
    private javax.swing.JButton jb_addt;
    private javax.swing.JTree jt_Principal;
    private javax.swing.JTextField tf_nequipo;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_puntos;
    private javax.swing.JTextField tf_tnombre;
    // End of variables declaration//GEN-END:variables
}
